set_excess_params:
  name: Set excess export parameters
  description: Sets the runtime parameters for excess export.
  target:
    entity:
      domain: sensor
      integration: cyg_skyline
  fields:
    target_soc_percent:
      name: Target SoC percentage
      description: The percentage of SoC to attempt to reach
      required: false
      advanced: false
      example: 85
      default: 100
